#!/usr/bin/env python3
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from collections import Counter

LANGS = {
    "bash": (".sh", ["comment"]),
    "c": (".c", ["comment"]),
    "cpp": (".cpp", ["comment"]),
    "csharp": (".cs", ["comment"]),
    "css": (".css", ["comment"]),
    "dart": (".dart", ["comment", "block_comment"]),
    "elixir": (".ex", ["comment"]),
    "go": (".go", ["comment"]),
    "haskell": (".hs", ["comment"]),
    "html": (".html", ["comment"]),
    "java": (".java", ["line_comment", "block_comment"]),
    "javascript": (".js", ["comment"]),
    "jsx": (".jsx", ["comment"]),
    "kotlin": (".kt", ["line_comment", "multiline_comment"]),
    "lua": (".lua", ["comment"]),
    "php": (".php", ["comment"]),
    "python": (".py", ["comment"]),
    "ruby": (".rb", ["comment"]),
    "rust": (".rs", ["line_comment", "block_comment", "doc_comment"]),
    "scala": (".scala", ["comment", "block_comment"]),
    "solidity": (".sol", ["comment"]),
    "swift": (".swift", ["comment", "multiline_comment"]),
    "tsx": (".tsx", ["comment"]),
    "typescript": (".ts", ["comment"]),
    "yaml": (".yaml", ["comment"]),
}

EXTS = {
    ".bash": "bash", ".sh": "bash", ".zsh": "bash",
    ".c": "c", ".h": "c",
    ".cc": "cpp", ".cpp": "cpp", ".cxx": "cpp", ".hh": "cpp", ".hpp": "cpp",
    ".cs": "csharp",
    ".css": "css",
    ".dart": "dart",
    ".ex": "elixir", ".exs": "elixir",
    ".go": "go",
    ".hs": "haskell",
    ".htm": "html", ".html": "html",
    ".java": "java",
    ".cjs": "javascript", ".js": "javascript", ".mjs": "javascript",
    ".jsx": "jsx",
    ".kt": "kotlin", ".kts": "kotlin",
    ".lua": "lua",
    ".php": "php",
    ".py": "python", ".pyi": "python",
    ".rb": "ruby",
    ".rs": "rust",
    ".scala": "scala", ".sc": "scala",
    ".sol": "solidity",
    ".swift": "swift",
    ".ts": "typescript", ".mts": "typescript", ".cts": "typescript",
    ".tsx": "tsx",
    ".yaml": "yaml", ".yml": "yaml",
}

ALLOW = re.compile(
    r"""
      ^\#!
    | \btype:\s*ignore
    | \bnoqa\b
    | \bpragma\b
    | \b(pylint|ruff|mypy|flake8|isort|pyright|bandit|coverage):
    | \bfmt:\s*(on|off)
    | \beslint(-disable|-enable)?\b
    | \@ts-(ignore|expect-error|nocheck)
    | \b(prettier|biome|istanbul|c8|v8|deepsource|sonar)[-\s]ignore
    | ^//\s*go:
    | \bnolint\b
    | \+build\b
    | \bSPDX-License-Identifier\b
    | \bcopyright\b
    | \blicensed under\b
    | -\*-\s*coding
    | \bvim:\s
    | \bshellcheck\s+disable
    | \@generated\b
    | \bcode generated by\b
    | \bDO NOT EDIT\b
    | \b(swiftlint|clang-format|rustfmt|gofmt):
    | \bsafety:\s
    | ^\S*\s*\#?(end)?region\b
    | \byaml-language-server:
    | \byamllint\s+disable
    """,
    re.IGNORECASE | re.VERBOSE,
)


def bail():
    sys.exit(0)


def comments(text, lang, ext, kinds):
    if not text.strip():
        return []
    rule = json.dumps(
        {
            "id": "nc",
            "language": lang,
            "rule": {"any": [{"kind": k} for k in kinds]},
        }
    )
    with tempfile.TemporaryDirectory() as d:
        path = os.path.join(d, "scan" + ext)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
        try:
            out = subprocess.run(
                [
                    "ast-grep", "scan",
                    "--inline-rules", rule,
                    "--json=compact",
                    "--no-ignore", "vcs",
                    "--no-ignore", "dot",
                    "--no-ignore", "hidden",
                    "--no-ignore", "parent",
                    "--no-ignore", "global",
                    "--no-ignore", "exclude",
                    path,
                ],
                capture_output=True,
                text=True,
                timeout=20,
            )
        except (OSError, subprocess.SubprocessError):
            raise RuntimeError("ast-grep failed")
    if out.returncode not in (0, 1) or not out.stdout.strip():
        if out.returncode not in (0, 1):
            raise RuntimeError(out.stderr.strip() or "ast-grep error")
        return []
    found = []
    for m in json.loads(out.stdout):
        found.append((m["range"]["start"]["line"] + 1, m["text"].strip()))
    found.sort()
    return found


def read(path):
    try:
        with open(path, encoding="utf-8") as fh:
            return fh.read()
    except (OSError, UnicodeDecodeError):
        return None


def notebook_cell(path, cell_id):
    nb = read(path)
    if nb is None:
        bail()
    try:
        cells = json.loads(nb)["cells"]
    except (ValueError, KeyError, TypeError):
        bail()
    for cell in cells:
        if cell.get("id") == cell_id:
            if cell.get("cell_type") != "code":
                bail()
            src = cell.get("source", "")
            return src if isinstance(src, str) else "".join(src)
    return ""


def main():
    if os.environ.get("CLAUDE_ALLOW_COMMENTS"):
        bail()
    if not shutil.which("ast-grep"):
        bail()
    try:
        payload = json.load(sys.stdin)
    except ValueError:
        bail()
    tool = payload.get("tool_name")
    ti = payload.get("tool_input") or {}

    if tool == "NotebookEdit":
        path = ti.get("notebook_path") or ""
        lang = "python"
        new = ti.get("new_source")
        if new is None:
            bail()
        mode = ti.get("edit_mode") or "replace"
        old = "" if mode == "insert" else notebook_cell(path, ti.get("cell_id"))
        if mode == "delete":
            bail()
    else:
        path = ti.get("file_path") or ""
        lang = EXTS.get(os.path.splitext(path)[1].lower())
        if lang is None:
            bail()
        if tool == "Write":
            new = ti.get("content")
            if new is None:
                bail()
            old = read(path) or ""
        elif tool == "Edit":
            old = read(path)
            if old is None:
                bail()
            find = ti.get("old_string")
            repl = ti.get("new_string")
            if find is None or repl is None or find not in old:
                bail()
            new = old.replace(find, repl) if ti.get("replace_all") else old.replace(find, repl, 1)
        else:
            bail()

    ext, kinds = LANGS[lang]
    try:
        before = Counter(t for _, t in comments(old, lang, ext, kinds))
        after = comments(new, lang, ext, kinds)
    except RuntimeError:
        bail()

    added = []
    for line, text in after:
        if before[text] > 0:
            before[text] -= 1
            continue
        if ALLOW.search(text):
            continue
        added.append((line, text))

    if not added:
        bail()

    listing = "\n".join(
        "  line {}: {}".format(line, text if len(text) <= 120 else text[:117] + "...")
        for line, text in added[:20]
    )
    if len(added) > 20:
        listing += "\n  ... and {} more".format(len(added) - 20)
    reason = (
        "Blocked by the no-comments hook: this edit to {} adds {} new comment(s).\n"
        "{}\n"
        "Your instructions say not to add comments to code. Resubmit the edit with "
        "the comments removed; keep the code itself unchanged otherwise.\n"
        "If the user explicitly asked for these comments, do not retry — tell them "
        "to re-run with CLAUDE_ALLOW_COMMENTS=1 set, or to disable the hook."
    ).format(path or "this file", len(added), listing)

    print(
        json.dumps(
            {
                "hookSpecificOutput": {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": "deny",
                    "permissionDecisionReason": reason,
                }
            }
        )
    )
    sys.exit(0)


try:
    main()
except SystemExit:
    raise
except Exception:
    sys.exit(0)
