"$schema" = "https://starship.rs/config-schema.json"

format = "$directory| $all"

[gcloud]
disabled = true

# this is very slow, even with core.fsmonitor and feature.manyfiles on
[git_status]
disabled= true

[kubernetes]
disabled = true
symbol = "k8s"
format = "[$symbol $context]($style) "
style = "blue bold"
