
[window]
decorations = "Buttonless"
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
normal = { family = "FiraCode Nerd Font" }
bold = { family = "FiraCode Nerd Font", style = "bold" }
italic = { family = "FiraCode Nerd Font", style = "italic" }

[cursor]
style = "Underline"

[colors.primary]
background = "#000000"

# same cursor as nvim
[colors.cursor]
cursor = "#ff0000"
text = "#ffffff"

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[general]
import = [
    "~/.config/alacritty/themes/themes/ayu_dark.toml",
    "~/.config/alacritty/os.toml"
]

[terminal]

shell = "zsh"

