import = [
    "~/.config/alacritty/themes/themes/ayu_dark.toml",
    "~/.config/alacritty/os.toml"
]

shell = "zsh"

[window]
decorations = "Buttonless"
startup_mode = "Maximized"
option_as_alt = "Both"
padding = { x = 3, y = 3 }

[font]
normal = { family = "FiraCode Nerd Font" }
bold = { family = "FiraCode Nerd Font", style = "bold" }
italic = { family = "FiraCode Nerd Font", style = "italic" }

[cursor]
style = "Underline"

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

