#!/usr/bin/env bash

DOTFILES_DIR=$(pwd)

: "${DOTFILES_ENV:=INSTALL}"
echo "Mode: $DOTFILES_ENV"

if [ "$DOTFILES_ENV" = "INSTALL" ]; then
    read -r -p "You're about to execute dotfiles install. Are you sure you want to proceed? [Y/n]" input
    
    case $input in
        [yY][eE][sS]|[yY])
            echo "Proceeding install"
        ;;
        *)
            echo "Aborting install"
        exit 1
    esac
fi

PYTHONPATH=$PYTHONPATH:DOTFILES_DIR

echo "Initializing installer"
apt -qq -y update > /dev/null

apt -qq -y install python3-pip > /dev/null
apt -qq -y install python3.7-venv > /dev/null

python3 -m pip install --quiet --upgrade pip
rm -rf ./venv
python3.7 -m venv venv
source ./venv/bin/activate
python3.7 -m pip install --quiet -r ./requirements.txt

python3.7 -m installer --env $DOTFILES_ENV $DOTFILES_DIR $@

rm -rf ./venv

if [ "$DOTFILES_ENV" = "TEST" ]; then
    echo "---> HOME LS"
    ls -a $HOME

    echo "---> ZSH LS"
    ls -a $HOME/.zsh
fi