#!/usr/bin/env bash

DOTFILES_DIR=$(pwd)

: "${DOTFILES_ENV:=INSTALL}"
echo "Mode: $DOTFILES_ENV"

if [ "$DOTFILES_ENV" = "INSTALL" ]; then
    read -r -p "You're about to execute dotfiles install. Are you sure you want to proceed? [Y/n]" input
    
    case $input in
        [yY][eE][sS]|[yY])
            echo "Proceeding install"
        ;;
        *)
            echo "Aborting install"
        exit 1
    esac
fi

PYTHONPATH=$PYTHONPATH:DOTFILES_DIR

apt -y install python3-pip
apt -y install python3-venv
python3 -m pip install --quiet --upgrade pip
rm -rf ./venv
python3 -m venv venv
source ./venv/bin/activate
python3 -m pip install --quiet -r ./installer/requirements.txt

python3 ./installer/installer.py $DOTFILES_DIR

rm -rf ./venv